### PR TITLE
CI/CD

### PR DESCRIPTION
**Pull request by pedrocamargo**

### CODE REVIEW

**Comment by pedrocamargo** [comment]
@janzill , imp[lementing CI showed a couple more issues that were not raised when running the tests locally. My impression is that this has something to do with how this is compiled in the runner VBs. locally, which I think it is an important issue to look into. Will do that a bit later.

**Comment by pedrocamargo** [comment]
@janzill Linux is throwing the same error...  VERY weird...

**Comment by pedrocamargo** [comment]
@janzill , what breaks the tests is the change from Pandas 1.2.x to 1.3.x.  The tests were passing on my machine because I had created the virtual environment before 1.3 had been released. I know they have been making a few changes to how they deal with types, so I will have to investigate this.

**Comment by pedrocamargo** [comment]
Found the issue. The code below for Passenger.py

image

Returns fields type float, which makes no sense for zone IDs.

This fixes it

image

But it is the wrong way of fixing it.

**Comment by pedrocamargo** [comment]
The issue was trying to do math with the default type of pandas indices...

**Review by janzill — APPROVED** [review]

**Pull request merged**
